<?php
include 'db.php';
$orderID = $_POST["order_id"];
$customerUserID = $_POST["customer_user_id"];
$driverUserID = $_POST["driver_user_id"];
$partnerID = $_POST["partner_id"];
$service = intval($_POST["service"]);
$status = intval($_POST["status"]);
$paymentType = intval($_POST["payment_type"]);
$paymentStatus = intval($_POST["payment_status"]);
$price = doubleval($_POST["price"]);
$latFrom = doubleval($_POST["lat_from"]);
$lngFrom = doubleval($_POST["lng_from"]);
$locationFrom = $_POST["location_from"];
$locationDetailFrom = $_POST["location_detail_from"];
$latTo = doubleval($_POST["lat_to"]);
$lngTo = doubleval($_POST["lng_to"]);
$locationTo = $_POST["location_to"];
$locationDetailTo = $_POST["location_detail_to"];
$dateInsert = $_POST["date_insert"];
$dateUpdate = $_POST["date_update"];
$notif = intval($_POST["notif"]);
$distance = doubleval($_POST["distance"]);
$fromIOS = intval($_POST["from_ios"]);
$sql = "INSERT INTO `order` (orderid, customer, driver, partner, service, status, payment_type, payment_status, price, lat_from, lng_from, location_from, location_detail_from, lat_to, lng_to, location_to, location_detail_to, date_insert, date_update, notif, distance, from_ios, notif_log) VALUES ('" . $orderID . "', '" . $customerUserID . "', '" . $driverUserID . "', '" . $partnerID . "', " . $service . ", " . $status . ", " . $paymentType . ", " . $paymentStatus . ", " . $price . ", " . $latFrom . ", " . $lngFrom . ", '" . $locationFrom . "', '" . $locationDetailFrom . "', " . $latTo . ", " . $lngTo . ", '" . $locationTo . "', '" . $locationDetailTo . "', '" . $dateInsert . "', '" . $dateUpdate . "', " . $notif . ", " . $distance . ", " . $fromIOS . ", '')";
pg_query($c, $sql);
$lastInsertID = mysqli_insert_id($c);
//echo $sql;
echo json_encode(pg_query($c, "SELECT * FROM `order` WHERE id=" . $lastInsertID)->fetch_assoc());
//echo $lastInsertID;
